# Úkol 2

Vytvořte kontingenční tabulky z datasetu Chocolate_Sales.csv.

- Spočítejte různé agregační funkce pro sloupce `Amount`, `Boxes Shipped`
- Shlukujte podle `Country`, `Product`

In [1]:
import pandas as pd

df = pd.read_csv('./data/Chocolate_Sales.csv')
df['Date'] = pd.to_datetime(df['Date'], format="%d/%m/%Y")
df['Amount'] = df['Amount'].str.replace("$","").str.replace(",","").astype(float)

df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3282 entries, 0 to 3281
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   3282 non-null   str
 1   Country        3282 non-null   str
 2   Product        3282 non-null   str
 3   Date           3282 non-null   datetime64[us]
 4   Amount         3282 non-null   float64
 5   Boxes Shipped  3282 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 154.0 KB

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,2022-01-04,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,2022-08-01,7896.0,94
2,Gigi Bohling,India,Peanut Butter Cubes,2022-07-07,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,2022-04-27,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,2022-02-24,13685.0,184

In [4]:
df_agg = df.groupby(['Country'])['Amount'].agg(['min', 'median', 'mean', 'max', 'var', 'std'])

df_agg

               min    median         mean       max           var          std
Country
Australia     63.0  5512.570  5929.177805  22943.37  1.669622e+07  4086.100882
Canada       210.0  4950.210  5863.801238  19449.02  1.721332e+07  4148.893930
India         28.0  4917.235  6057.483388  26170.95  2.179576e+07  4668.592783
New Zealand    7.0  5306.480  5864.458651  21381.14  1.780002e+07  4219.007194
UK             7.0  5491.335  6302.226404  22558.88  1.997452e+07  4469.286795
USA           70.0  5220.690  6171.057896  19995.68  2.259937e+07  4753.879947

In [13]:
df_pivot = df.pivot_table(
    values=['Amount', 'Boxes Shipped'],
    index=['Country', 'Product'],
    #aggfunc=['min', 'median', 'mean', 'max', 'var', 'std']
    aggfunc={
        'Amount': ['min', 'median', 'mean', 'max', 'var', 'std'],
        'Boxes Shipped': ['min', 'median', 'mean', 'max', 'var', 'std']
    }
)

df_pivot

                                 Amount                                  \
                                    max         mean    median      min
Country   Product
Australia 50% Dark Bites       15593.50  5834.725417  5207.095   504.00
          70% Dark Bites        8260.58  4723.720741  5859.000   237.57
          85% Dark Bars         9452.18  5141.597083  4470.520  1575.00
          99% Dark & Pure      12285.41  5340.836970  4669.000   112.00
          After Nines           8265.41  4269.462381  3446.840    63.00
...                                 ...          ...       ...      ...
USA       Peanut Butter Cubes  15722.43  5066.082857  1736.000   280.00
          Raspberry Choco      17037.09  8034.170606  7049.320   672.00
          Smooth Sliky Salty   17662.05  6035.009167  3376.055   504.00
          Spicy Special Slims  12450.24  3406.239583  1947.550    77.00
          White Choc           14360.42  7246.458000  6440.175  2030.00

                                                         Boxes Shipped  \
                                       std           var           max
Country   Product
Australia 50% Dark Bites       4392.838617  1.929703e+07           778
          70% Dark Bites       2557.506011  6.540837e+06           509
          85% Dark Bars        2481.792910  6.159296e+06           453
          99% Dark & Pure      3484.399109  1.214104e+07           237
          After Nines          2649.416094  7.019406e+06           306
...                                    ...           ...           ...
USA       Peanut Butter Cubes  5239.753743  2.745502e+07           363
          Raspberry Choco      5292.732240  2.801301e+07           354
          Smooth Sliky Salty   5234.957248  2.740478e+07           354
          Spicy Special Slims  3681.788034  1.355556e+07           418
          White Choc           3170.039296  1.004915e+07           349

                                                                   \
                                     mean median  min         std
Country   Product
Australia 50% Dark Bites       201.916667  142.0    6  192.832618
          70% Dark Bites       236.629630  227.0  103  135.421606
          85% Dark Bars        152.041667   65.5   14  152.672277
          99% Dark & Pure      124.727273  128.0   18   63.990855
          After Nines          130.047619   77.0   26  108.784409
...                                   ...    ...  ...         ...
USA       Peanut Butter Cubes  174.571429  137.0   18  122.977873
          Raspberry Choco      138.484848  139.0   17   99.646287
          Smooth Sliky Salty   169.375000  150.0   86   80.876617
          Spicy Special Slims  175.500000  168.5    5  128.347016
          White Choc           121.266667  120.5    2  100.068230


                                        var
Country   Product
Australia 50% Dark Bites       37184.418440
          70% Dark Bites       18339.011396
          85% Dark Bars        23308.824275
          99% Dark & Pure       4094.829545
          After Nines          11834.047619
...                                     ...
USA       Peanut Butter Cubes  15123.557143
          Raspberry Choco       9929.382576
          Smooth Sliky Salty    6541.027174
          Spicy Special Slims  16472.956522
          White Choc           10013.650575

[132 rows x 12 columns]

## Uložení výsledku

In [14]:
df_pivot.to_csv('./data/Chocolate_Sales_pivot_table.csv')