In [1]:
import pandas as pd
from pandas.conftest import dropna

weather = pd.read_csv('./data/pydata_data.csv', sep=";")

weather['YEAR'] = weather['DATE'].str[:4].astype(int)
weather['MONTH'] = weather['DATE'].str[5:7].astype(int)
weather['DAY'] = weather['DATE'].str[8:].astype(int)

weather['DATE'] = pd.to_datetime(weather['DATE'])

weather.info()
weather.head()

<class 'pandas.DataFrame'>
RangeIndex: 67834 entries, 0 to 67833
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  67834 non-null  str
 1   NAME     67834 non-null  str
 2   DATE     67834 non-null  datetime64[us]
 3   PRCP     56483 non-null  float64
 4   SNWD     17540 non-null  float64
 5   TAVG     59664 non-null  float64
 6   TMAX     51147 non-null  float64
 7   TMIN     50830 non-null  float64
 8   YEAR     67834 non-null  int64
 9   MONTH    67834 non-null  int64
 10  DAY      67834 non-null  int64
dtypes: datetime64[us](1), float64(5), int64(3), str(2)
memory usage: 5.7 MB

,STATION,NAME,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY
0,GME00132274,PIDING,2006-12-01,0.0,0.0,NaN,4.2,1.0,2006,12,1
1,GME00132274,PIDING,2006-12-02,0.0,0.0,NaN,1.8,-1.7,2006,12,2
2,GME00132274,PIDING,2006-12-03,0.0,0.0,NaN,5.1,-4.6,2006,12,3
3,GME00132274,PIDING,2006-12-04,19.0,0.0,NaN,8.3,-0.9,2006,12,4
4,GME00132274,PIDING,2006-12-05,0.0,0.0,NaN,12.0,0.9,2006,12,5

# Statistiky

In [2]:
weather.describe()

,DATE,PRCP,SNWD,TAVG,TMAX,TMIN,YEAR,MONTH,DAY
count,67834,56483.000000,17540.000000,59664.000000,51147.000000,50830.000000,67834.000000,67834.000000,67834.000000
mean,2010-06-16 09:58:10.249727,2.390054,29.513512,10.169048,15.272442,5.724139,2009.960079,6.490300,15.709143
min,2000-01-01 00:00:00,0.000000,0.000000,-21.600000,-17.400000,-23.600000,2000.000000,1.000000,1.000000
25%,2005-02-27 00:00:00,0.000000,0.000000,3.600000,7.700000,0.200000,2005.000000,3.000000,8.000000
50%,2010-06-30 00:00:00,0.000000,0.000000,10.500000,16.100000,6.000000,2010.000000,7.000000,16.000000
75%,2015-09-15 00:00:00,1.800000,30.000000,16.900000,22.900000,11.800000,2015.000000,9.000000,23.000000
max,2020-11-18 00:00:00,140.000000,1400.000000,30.300000,39.600000,25.300000,2020.000000,12.000000,31.000000
std,NaN,6.191885,59.993963,8.342663,9.508819,7.481063,6.037180,3.439442,8.806859

In [6]:
print(f"Šikmost: {weather['TAVG'].skew()}")
print(f"Špičatost: {weather['TAVG'].kurt()}")

Šikmost: -0.16807977247680042
Špičatost: -0.7637311845008985

## Ověření normality

In [14]:
from scipy import stats

stat, p_value = stats.shapiro(weather['TMIN'], nan_policy='omit')

print(f"stat = {stat}, p_value = {p_value}")

stat = 0.9844047254599421, p_value = 3.6014002562638773e-56

C:\Users\Student\PycharmProjects\ICTPro_Pydata1\.venv\Lib\site-packages\scipy\stats\_axis_nan_policy.py:592: UserWarning: scipy.stats.shapiro: For N > 5000, computed p-value may not be accurate. Current N is 50830.
  res = hypotest_fun_out(*samples, **kwds)